spring:
  datasource:
    url: jdbc:mysql://182.92.184.249:3306/test
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#      host: 127.0.0.1
#      port: 6379
#      password: test
server:
  port: 8091
